version: '3.3'

services:
  postgres:
    image: postgres:15beta3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - musicalbumguide_network

  backend:
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:7000
    ports:
      - "7000:7000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - musicalbumguide_network

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - musicalbumguide_network
  
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   command: python main.py
  #   depends_on:
  #     - nginx
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   networks:
  #     - musicalbumguide_network

volumes:
  postgres_data:

networks:
  musicalbumguide_network:
