version: '3.8'

services:
  postgres-local:
    image: postgres:15beta3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .local.env

volumes:
  postgres_data:
